### ISSUE TITLE
Module doesn't give any output in frontend

### ISSUE THREAD

**Issue by robhuijben** [Elfangor93/mod_tinyslider#1]
The module doesn't give any output in the frontend. I don't know if it is not ready to use in production yet, otherwise I am willing to help getting it fixed and ready.

**Comment by Elfangor93** [comment]
I am using the module on several live pages without problems.
Do you get any errors?

**Comment by robhuijben** [comment]
Missed a typo in my custom theme. I got some output now, but I am stuck with an error in my console:

`Uncaught ReferenceError: tns is not defined`

This seems to be caused by `let slider = tns(options);`.

When I load the tinyslider library directly from cloudflare, I can see the error is gone but there are no images displayed in the frontend.

**Comment by Elfangor93** [comment]
Looks as if the tinyslider library is not properly loaded.
Can you post the link to the website you are showing the slideshow?

**Comment by robhuijben** [comment]
I am developing locally, but I opened an ngrok tunnel which you can use to see the frontend.

https://afc3-87-99-184-239.ngrok-free.app

**Comment by Elfangor93** [comment]
This line of code seems to be missing in your site.
https://github.com/Elfangor93/mod_tinyslider/blob/61318c24bc803ef1afc6f0f9c4467b6a604b3898/tmpl/default.php#L33

Have you created an override of the modules template file?
Your html looks different...

**Comment by Elfangor93** [comment]
Lines 33 until 52 are required for the slideshow to work.
If you integrate the slideshow directly over cloudflare you are probably integrating a newer version of the library. Then you maybe have to adjust the html structure based on the documentation of the new library version.

**Comment by robhuijben** [comment]
I think the issue is in the page source on line 185. The file with path `modules/mod_tinyslider/tmpl/default.php` does contain the line ` <script src="<?php echo Uri::base(true).'/media/mod_tinyslider/js/tiny-slider.min.js'; ?>"></script>`. But if you look at the src link in the frontend you can see that it doesn't prepend URI:base to the source URL. Trying to open the file results in a 404.

**Comment by Elfangor93** [comment]
Yes, correct. Seems like `/media/mod_tinyslider/js/tiny-slider.min.js` was not copied correctly during module installation. Therefore probably the whole `js` and `css` folders are missing in `/media/mod_tinyslider/`, right?
As a quick fix, you could copy `/media/js` and `/media/css` by hand to `/media/mod_tinyslider/js` resp `/media/mod_tinyslider/css`.

**Comment by robhuijben** [comment]
Yes, got it working now. That was the issue. Thanks for your time and effort.

**Comment by Elfangor93** [comment]
Thank you for reporting the issue.
It is a misconfiguration of the module xml file which leads to a wrong installation.

**Comment by Elfangor93** [comment]
>Thank you for reporting the issue.
It is a misconfiguration of the module xml file which leads to a wrong installation.

I just tested the installation of the module on several joomla installations. The media folder was always created correctly and the module works from the beginning. So in principle the module xml file is fine and the installation works correctly...
