### ISSUE TITLE
[J4.4.2] Bilder-Pfad bei Mehrsprachigkeit

### ISSUE THREAD

**Issue by 7at1blow** [Elfangor93/mod_tinyslider#2]
Das TinySlider nutzt derzeit bei Mehrsprachigkeit einer Site nicht den im BE des Moduls eingegebenen Bilderpfad, also z. B.

`images/sliderbilder`,

sondern stattdessen einen abgewandelten Bilderpfad, also z. B. 

`en/images/sliderbilder` oder
`de/images/sliderbilder` usw.

Das bewirkt, dass die Bilder des gewünschten Zielverzeichnisses nicht gefunden werden und dadurch im Frontend im Modul auch nicht angezeigt werden.

In der Browser-Konsole zeigt sich dann beim JS ein 404 bzgl. des Ladens der Bilder. Klick auf diese JS-404-Fehlermeldung liefert den Hinweis, dass bei dem Bilderpfad ein o. g. `en/` oder `de/` usw. vorgestellt wurde.

**Comment by Elfangor93** [comment]
Das Problem ist grundsätzlich, wenn man Bilder mit relativen Pfaden in einer mehrsprachigen Joomla Seite einfügt:
https://joomla.stackexchange.com/questions/5863/loading-images-in-a-multi-language-multi-site-configuration

**Comment by 7at1blow** [comment]
Mmmh, die Nachricht ist 9 Jahre alt. Und bezieht sich auf J 3.x.
Vielleicht hat sich die Situation bei J 4.x (oder 5.x) ja etwas geändert, so dass das Problem behebbar/einfacher behebbar ist.

**Comment by Elfangor93** [comment]
@7at1blow Ich habe eine Code-Änderung als Pull-Request gestartet, welcher das Problem bei der Mehrsprachigkeit beheben sollte. Kannst du den Pull-Request testen? Wenn das so klappt, werde ich die Änderung offiziell ins Modul übernehmen.
Pull-Request: https://github.com/Elfangor93/mod_tinyslider/pull/3

**Comment by 7at1blow** [comment]
PR erfolgreich getestet, Dankeschön!
